version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: triagil
      POSTGRES_PASSWORD: triagil
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://triagil:triagil@postgres/desafio
    depends_on:
      - postgres

volumes:
  postgres_data:
